GET {{host}}/api/public/categories
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/api/public/categories?id=1
Accept: application/json
Authorization: Bearer {{auth_token}}
###

POST {{host}}/api/categories
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "testing"
}

###

PUT {{host}}/api/admin/categories/update
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Category test
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="not-found-image.png"
Content-Type: image/jpeg

< ./../image/not-found-image.png
--WebAppBoundary--
###

DELETE {{host}}/api/admin/categories/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "1"
}
###
