GET {{host}}/api/public/info/page?id=1
Accept: application/json

###

GET {{host}}/api/public/info/page
Accept: application/json

###

GET {{host}}/api/public/info/page?page=Home
Accept: application/json

###

POST {{host}}/api/info/page
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "hi",
  "content": "this",
  "reference": "Home"
}

###

PUT {{host}}/api/info/page
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "10",
  "title": "hi 2",
  "content": "this 2",
  "reference": "Home 2"
}

###

DELETE {{host}}/api/info/page
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "1"
}

###
