GET {{host}}/api/public/endpoints
Accept: application/json
Authorization: Bearer {{auth_token}}

###
GET {{host}}/api/public/base
Accept: application/

###
GET {{host}}/src/uploads/granos-1.jpg
Accept: application/

###
