POST {{host}}/api/categories/products
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "product_id": "1",
  "category_id": "2"
}

###

PUT {{host}}/api/categories/products
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "product_id": "3",
  "category_id": "26"
}

###

DELETE {{host}}/api/categories/products
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "product_id": "26",
  "category_id": "1"
}

###
