GET {{host}}/api/admin/transport/getID/4
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/api/admin/transport/getAll
Accept: application/json
Authorization: Bearer {{auth_token}}
###

POST {{host}}/api/images/reg
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="product_id"
Content-Type: text/plain

5

--WebAppBoundary
Content-Disposition: form-data; name="size"
Content-Type: text/plain

4mm x 4mm

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="not-found-image.png"
Content-Type: image/jpeg

< ./../image/not-found-image.png
--WebAppBoundary--

###

POST {{host}}/api/transport/register
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name_truck": "Ivans",
  "user_iduser": "5"
}
###

PUT {{host}}/api/transport/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idtransport": "3",
  "name_truck": "Ivans",
  "user_iduser": "5"
}
###

DELETE {{host}}/api/transport/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idtransport": "3"
}
###
