GET {{host}}/api/public/transactions
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/transactions
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/transactions?payment=Paypal
Accept: application/json
Authorization: Bearer {{auth_token}}

###

POST {{host}}/api/transactions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "address"           : "Buenos Aires, Argentina",
  "map_lng"           : -58.37745132321935,
  "map_lat"           : -34.599649349384904,
  "order_id_paypal"   : "1KG39489F9664412V",
  "processor"         : "Credit card",
  "processor_trans_id": 1,
  "quantity"          : 1,
  "product_id"        : "1",
  "cart_id"           : "3",
  "user_id"           : "3",
  "total"             : "250.25",
  "subtotal"          : "250.25",
  "chat_id"           : "nZasjnCG69jGBH0cdWjE",
  "token_stripe"      : {
    "id"       : "tok_1F9BDqCYq3mncs6kElNOHmGF",
    "object"   : "token",
    "card"     : {
      "id"                 : "card_1F9BDqCYq3mncs6kdgFjfQHE",
      "object"             : "card",
      "address_city"       : null,
      "address_country"    : null,
      "address_line1"      : null,
      "address_line1_check": null,
      "address_line2"      : null,
      "address_state"      : null,
      "address_zip"        : null,
      "address_zip_check"  : null,
      "brand"              : "Visa",
      "country"            : "US",
      "cvc_check"          : "pass",
      "dynamic_last4"      : null,
      "exp_month"          : 2,
      "exp_year"           : 2020,
      "funding"            : "credit",
      "last4"              : "4242",
      "metadata"           : {},
      "name"               : "ivans21@gmail.com",
      "tokenization_method": null
    },
    "client_ip": "186.185.37.52",
    "created"  : 1566222514,
    "email"    : "ivans21@gmail.com",
    "livemode" : false,
    "type"     : "card",
    "used"     : false
  }
}

###

POST {{host}}/api/transactions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "address"           : "Buenos Aires, Argentina",
  "map_lng"           : -58.37745132321935,
  "map_lat"           : -34.599649349384904,
  "order_id_paypal"   : "1KG39489F9664412V",
  "processor"         : "Credit card",
  "processor_trans_id": 1,
  "quantity"          : 1,
  "product_id"        : "1",
  "cart_id"           : "9",
  "user_id"           : "3",
  "total"             : "250.25",
  "subtotal"          : "250.25",
  "chat_id"           : "nZasjnCG69jGBH0cdWjE",
  "token_stripe"      : {
    "id"       : "tok_1F9BDqCYq3mncs6kElNOHmGF",
    "object"   : "token",
    "card"     : {
      "id"                 : "card_1F9BDqCYq3mncs6kdgFjfQHE",
      "object"             : "card",
      "address_city"       : null,
      "address_country"    : null,
      "address_line1"      : null,
      "address_line1_check": null,
      "address_line2"      : null,
      "address_state"      : null,
      "address_zip"        : null,
      "address_zip_check"  : null,
      "brand"              : "Visa",
      "country"            : "US",
      "cvc_check"          : "pass",
      "dynamic_last4"      : null,
      "exp_month"          : 2,
      "exp_year"           : 2020,
      "funding"            : "credit",
      "last4"              : "4242",
      "metadata"           : {},
      "name"               : "ivans21@gmail.com",
      "tokenization_method": null
    },
    "client_ip": "186.185.37.52",
    "created"  : 1566222514,
    "email"    : "ivans21@gmail.com",
    "livemode" : false,
    "type"     : "card",
    "used"     : false
  }
}

###

PUT {{host}}/api/transaction
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id"                : "",
  "code"              : 1,
  "processor"         : "Amazon",
  "processor_trans_id": 1,
  "cc_num"            : "121",
  "cc_type"           : "211",
  "start_date"        : "2019-05-15",
  "end_date"          : "2019-05-23",
  "user_id"           : "",
  "total"             : 2700,
  "subtotal"          : 2700
}

###

DELETE {{host}}/api/transaction
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "paymentToken": "EC-1SS63624VS356304E",
  "orderID"     : "EC-1SS63624VS356304E",
  "payerID"     : "C5DBVRV6AYCQ8",
  "paymentID"   : "PAY-9HM85195VA555131HLTQRHDY",
  "intent"      : "authorize"
}

###
