POST {{host}}/api/public/users/login
Content-Type: application/json

{
  "email"   : "client@gmail.com",
  "password": "123456"
}

> {% client.global.set("auth_token", response.body.data.token); %}

###

GET {{host}}/api/users?type=client
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/users/email?email=client2@gmail.com
Accept: application/json

###

### TODO: how to public folder in express
GET {{host}}/public/images/not-found-image.png
Accept: application/json

###

GET {{host}}/api/users?id=2
Accept: application/json
Authorization: Bearer {{auth_token}}

###

POST {{host}}/api/users/photo
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="id"
Content-Type: text/plain

1

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="not-found-image.png"
Content-Type: image/jpeg

< ./../image/not-found-image.png
--WebAppBoundary--

###

POST {{host}}/api/public/users/register
Content-Type: application/json

{
  "email"      : "ivans1041@gmail.com",
  "pass_repeat": "123456",
  "password"   : "123456"
}

###

PUT {{host}}/api/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id"        : "17",
  "first_name": "ivans",
  "role_id"   : 2
}

###

PUT {{host}}/api/users/password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id"         : "2",
  "newPassword": "123456",
  "password"   : "1234567"
}

###

DELETE {{host}}/api/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "1"
}

###
