POST {{host}}/api/public/users/login
Content-Type: application/json

{
  "email": "pedro46@gmail.com",
  "password": "12345678"
}

> {% client.global.set("auth_token", response.body.data.token); %}

###

GET {{host}}/api/users
Accept: application/json
Authorization: {{auth_token}}

###

### TODO: how to public folder in express
GET {{host}}/public/images/not-found-image.png
Accept: application/json

###

GET {{host}}/api/public/info
Accept: application/json

###

GET {{host}}/api/users?id=2
Accept: application/json
Authorization: {{auth_token}}

###

POST {{host}}/api/public/users/register
Content-Type: application/json

{
  "id": "",
  "email": "pedro46@gmail.com",
  "first_name": "Pedro",
  "last_name": "Rodriguez",
  "password": "12345678",
  "address": "Calle Santa Rita",
  "phone": "4164318061",
  "city": "Maracay",
  "state": "Aragua",
  "country": "Venezuela",
  "country_code": "",
  "postal_code": "2120",
  "role_id": 2
}

###

PUT {{host}}/api/users
Content-Type: application/json
Authorization: {{auth_token}}

{
  "id": "17",
  "first_name": "ivans",
  "role_id": 2
}

###

PUT {{host}}/api/users/password
Content-Type: application/json
Authorization: {{auth_token}}

{
  "id": "17",
  "email": "pedro46@gmail.com",
  "password": "12345678"
}

###

DELETE {{host}}/api/users
Content-Type: application/json
Authorization: {{auth_token}}

{
  "id": "1"
}

###
